# Generated by Django 3.2.4 on 2021-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folderdesc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
