# Generated by Django 3.2.4 on 2021-06-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googledriveapp', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='googledriveapp.folder'),
            preserve_default=False,
        ),
    ]
